export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';
export const REMOVE_NEW_CATEGORY = 'REMOVE_NEW_CATEGORY';
export const UPDATE_CATEGORY_FIELDS = 'UPDATE_CATEGORY_FIELDS';
export const ADD_NEW_FIELD_CATEGORY = 'ADD_NEW_FIELD_CATEGORY';
export const UPDATE_CATEGORY_FIELD_TYPE = 'UPDATE_CATEGORY_FIELD_TYPE';