export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';
export const REMOVE_NEW_CATEGORY = 'REMOVE_NEW_CATEGORY';
export const UPDATE_CATEGORY_FIELDS = 'UPDATE_CATEGORY_FIELDS';
export const ADD_NEW_FIELD_CATEGORY = 'ADD_NEW_FIELD_CATEGORY';
export const UPDATE_CATEGORY_FIELD_TYPE = 'UPDATE_CATEGORY_FIELD_TYPE';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const REMOVE_NEW_PRODUCT = 'REMOVE_NEW_PRODUCT';
export const UPDATE_PRODUCT_TITLES = 'UPDATE_PRODUCT_TITLES';
export const UPDATE_PRODUCT_FIELDS = 'UPDATE_PRODUCT_FIELDS';
